### ISSUE TITLE
TotalSegmentator exits with code 2

### ISSUE THREAD

**Issue by jumbojing** [lassoan/SlicerTotalSegmentator#33]
```
Traceback (most recent call last):
  File "/Applications/Slicer3.app/Contents/bin/Python/slicer/util.py", line 2967, in tryWithErrorDisplay
    yield
  File "/Users/liguimei/Documents/GitHub/SlicerTotalSegmentator/TotalSegmentator/TotalSegmentator.py", line 271, in onApplyButton
    self.logic.process(self.ui.inputVolumeSelector.currentNode(), self.ui.outputSegmentationSelector.currentNode(),
  File "/Users/liguimei/Documents/GitHub/SlicerTotalSegmentator/TotalSegmentator/TotalSegmentator.py", line 868, in process
    self.logProcessOutput(proc)
  File "/Users/liguimei/Documents/GitHub/SlicerTotalSegmentator/TotalSegmentator/TotalSegmentator.py", line 701, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['/Applications/Slicer3.app/Contents/bin/../bin/PythonSlicer', '/Applications/Slicer3.app/Contents/lib/Python/bin/TotalSegmentator', '-i', '/private/var/folders/9b/mhf79phj3ss95qk4p1_vw6gh0000gn/T/Slicer-liguimei/__SlicerTemp__2023-10-02_06+12+36.781/total-segmentator-input.nii', '-o', '/private/var/folders/9b/mhf79phj3ss95qk4p1_vw6gh0000gn/T/Slicer-liguimei/__SlicerTemp__2023-10-02_06+12+36.781/segmentation', '--ml', '--task', 'bones_tissue_test']' returned non-zero exit status 2.
```

```
Traceback (most recent call last):
  File "/Applications/Slicer3.app/Contents/bin/Python/slicer/util.py", line 2967, in tryWithErrorDisplay
    yield
  File "/Users/liguimei/Documents/GitHub/SlicerTotalSegmentator/TotalSegmentator/TotalSegmentator.py", line 271, in onApplyButton
    self.logic.process(self.ui.inputVolumeSelector.currentNode(), self.ui.outputSegmentationSelector.currentNode(),
  File "/Users/liguimei/Documents/GitHub/SlicerTotalSegmentator/TotalSegmentator/TotalSegmentator.py", line 868, in process
    self.logProcessOutput(proc)
  File "/Users/liguimei/Documents/GitHub/SlicerTotalSegmentator/TotalSegmentator/TotalSegmentator.py", line 701, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['/Applications/Slicer3.app/Contents/bin/../bin/PythonSlicer', '/Applications/Slicer3.app/Contents/lib/Python/bin/TotalSegmentator', '-i', '/private/var/folders/9b/mhf79phj3ss95qk4p1_vw6gh0000gn/T/Slicer-liguimei/__SlicerTemp__2023-10-02_06+06+56.467/total-segmentator-input.nii', '-o', '/private/var/folders/9b/mhf79phj3ss95qk4p1_vw6gh0000gn/T/Slicer-liguimei/__SlicerTemp__2023-10-02_06+06+56.467/segmentation', '--ml', '--task', 'test']' returned non-zero exit status 1.
```

**Comment by lassoan** [comment]
This does not contain the actual error message, so we cannot investigate the problem. Please check if you can find more details in the output section of the module or in the application log.

**Comment by lassoan** [comment]
Installation of TotalSegmentator and dependencies have been made more robust, everything should work well now when starting from a clean installation.
