### ISSUE TITLE
Force reinstall fail...

### ISSUE THREAD

**Issue by jumbojing** [lassoan/SlicerTotalSegmentator#34]
```
Traceback (most recent call last):
  File "/Users/liguimei/Documents/GitHub/SlicerTotalSegmentator/TotalSegmentator/TotalSegmentator.py", line 284, in onPackageUpgrade
    self.logic.setupPythonRequirements(upgrade=True)
  File "/Users/liguimei/Documents/GitHub/SlicerTotalSegmentator/TotalSegmentator/TotalSegmentator.py", line 659, in setupPythonRequirements
    slicer.util.pip_install("git+https://github.com/wasserth/TotalSegmentator.git")
  File "/Applications/Slicer.app/Contents/bin/Python/slicer/util.py", line 3613, in pip_install
    _executePythonModule('pip', args)
  File "/Applications/Slicer.app/Contents/bin/Python/slicer/util.py", line 3575, in _executePythonModule
    logProcessOutput(proc)
  File "/Applications/Slicer.app/Contents/bin/Python/slicer/util.py", line 3544, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['/Applications/Slicer.app/Contents/bin/../bin/PythonSlicer', '-m', 'pip', 'install', 'git+https://github.com/wasserth/TotalSegmentator.git']' returned non-zero exit status 1.
```
I want to 'use latest development version' and 'Force reinstall'... but failed 👆🏻

**Comment by lassoan** [comment]
Latest development version is now using TotalSegmentator v2, which is not compatible with the module yet. We are already working on switching to v2 - see here:

https://github.com/lassoan/SlicerTotalSegmentator/pull/38
