### ISSUE TITLE
utf-8 codec cant decode byte - invalid start byte

### ISSUE THREAD

**Issue by RURon** [lassoan/SlicerTotalSegmentator#5]
Hello, when I try to use the plugin with the supplied CTA abdomen, I get this error:
This is on Windows 10-64Bit - german locale.

```
Traceback (most recent call last):
  File "C:\Users\Ernie\AppData\Local\NA-MIC\Slicer 5.2.1\bin\Python\slicer\util.py", line 2961, in tryWithErrorDisplay
    yield
  File "C:/Users/Ernie/AppData/Local/NA-MIC/Slicer 5.2.1/NA-MIC/Extensions-31317/TotalSegmentator/lib/Slicer-5.2/qt-scripted-modules/TotalSegmentator.py", line 245, in onApplyButton
    self.logic.process(self.ui.inputVolumeSelector.currentNode(), self.ui.outputSegmentationSelector.currentNode(),
  File "C:/Users/Ernie/AppData/Local/NA-MIC/Slicer 5.2.1/NA-MIC/Extensions-31317/TotalSegmentator/lib/Slicer-5.2/qt-scripted-modules/TotalSegmentator.py", line 516, in process
    self.logProcessOutput(proc)
  File "C:/Users/Ernie/AppData/Local/NA-MIC/Slicer 5.2.1/NA-MIC/Extensions-31317/TotalSegmentator/lib/Slicer-5.2/qt-scripted-modules/TotalSegmentator.py", line 418, in logProcessOutput
    line = proc.stdout.readline()
  File "C:\Users/Ernie/AppData/Local/NA-MIC/Slicer 5.2.1/bin/../lib/Python/Lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 366: invalid start byte
```

**Comment by lassoan** [comment]
Thanks for reporting. The problem is fixed now. You can either update the extension via the Extensions Manager tomorrow or make the [change](https://github.com/lassoan/SlicerTotalSegmentator/commit/bda331459bc59b4a9883bd6fce2a8e0f78908173) in your local TotalSegmentator.py file now.
