### ISSUE TITLE
Basic error

### ISSUE THREAD

**Issue by shion0007** [lassoan/SlicerTotalSegmentator#6]
I'm using Slicer ver5.2 and trying to use TotalSegmentor, but I'm getting the error below. How would you like to fix it? Sorry for the basic question.

Command '['C:/Users/Owner/AppData/Local/NA-MIC/Slicer 5.2.1/bin/../bin\\PythonSlicer.EXE', '-m', 'pip', 'install', 'git+https://github.com/wasserth/TotalSegmentator.git', '--no-deps']' returned non-zero exit status 1.

Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\NA-MIC\Slicer 5.2.1\bin\Python\slicer\util.py", line 2961, in tryWithErrorDisplay
    yield
  File "C:/Users/Owner/AppData/Local/NA-MIC/Slicer 5.2.1/NA-MIC/Extensions-31317/TotalSegmentator/lib/Slicer-5.2/qt-scripted-modules/TotalSegmentator.py", line 238, in onApplyButton
    self.logic.setupPythonRequirements()
  File "C:/Users/Owner/AppData/Local/NA-MIC/Slicer 5.2.1/NA-MIC/Extensions-31317/TotalSegmentator/lib/Slicer-5.2/qt-scripted-modules/TotalSegmentator.py", line 372, in setupPythonRequirements
    slicer.util.pip_install(totalSegmentatorPackage + " --no-deps" + (" --upgrade" if upgrade else ""))
  File "C:\Users\Owner\AppData\Local\NA-MIC\Slicer 5.2.1\bin\Python\slicer\util.py", line 3571, in pip_install
    _executePythonModule('pip', args)
  File "C:\Users\Owner\AppData\Local\NA-MIC\Slicer 5.2.1\bin\Python\slicer\util.py", line 3533, in _executePythonModule
    logProcessOutput(proc)
  File "C:\Users\Owner\AppData\Local\NA-MIC\Slicer 5.2.1\bin\Python\slicer\util.py", line 3502, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['C:/Users/Owner/AppData/Local/NA-MIC/Slicer 5.2.1/bin/../bin\\PythonSlicer.EXE', '-m', 'pip', 'install', 'git+https://github.com/wasserth/TotalSegmentator.git', '--no-deps']' returned non-zero exit status 1.

**Comment by lassoan** [comment]
Please check the error log (menu: Help / Report a bug) to see if there is any additional details about what went wrong (run out of disk space, some files are in use, etc).

If you don't see any messages then run from the Windows command prompt:

    C:/Users/Owner/AppData/Local/NA-MIC/Slicer 5.2.1/PythonSlicer.EXE -m pip install git+https://github.com/wasserth/TotalSegmentator.git --no-deps
